Raklechitca-Team/raklechitca

.vscode/settings.json, components/InstaBlock.vue, components/ui/Cover.vue, pages/index.vue
=> InstaBlockDemo

components/Cardlist/Card.vue, components/Cardlist/CardList.vue, components/ui/PageNumber.vue, pages/stories/index.vue
немного исправила страницы со всеми историями + добавила на 320px 
добавила заголовок
жду аппрува инпута с поиском, добавлю его вечером перед отправкой, если там не будет много исправлений (либо в следующее ревью)
=> скорректировала верстку страницы со всеми историями

components/Cardlist/Card.vue, components/Cardlist/CardList.vue, components/ui/PageNumber.vue, pages/stories/_id.vue, pages/stories/index.vue
поправила немного верстку в _id (отдельная история)
=> Single story

components/TellStory.vue
добавила кнопку MainButton в блок TellStory, адаптировала ее, текст не меняла пока
=> добавила кнопку в tellstory и адаптировала

components/Cardlist/Card.vue, pages/stories/_id.vue
=> adaptive story

components/LeaveContact.vue, components/Popup.vue, components/ui/ButtonFillForm.vue, components/ui/MoreArticles.vue, layouts/default.vue
=> Окошко попап без конфликтов (я надеюсь)

components/LeaveContact.vue, components/Popup.vue, components/Search.vue, components/svg/history__button_img.svg, components/ui/ButtonFillForm.vue, components/ui/MoreArticles.vue, layouts/default.vue
Акция! Теперь без конфликтов!!!
Также адаптив и все дела
=> Инпут поиска

components/LeaveContact.vue, components/TellStory.vue, layouts/default.vue, store/popup.js
Чуть улучшили, плюс есть скрипт (спасибо Полина!)
=> Contact popup

components/Quiz.vue, components/Stories.vue, components/Video/Video.vue, components/Video/VideoIframe.vue, components/instaBlock/InstaBlock.vue, components/ui/Menu.vue, components/ui/MoreArticles.vue, pages/stories/index.vue
сделала заголовок Инстаграм ссылкой, подключила политику, убрала лишние отступы, пофиксила кнопку в меню, убрала рамку у видео
=> ещё немного изменений

components/instaBlock/InstaBlock.vue, plugins/swiper.js
Добавила ссылку для блока инстаграм
=> Hookup contact

components/Footer/Footer.vue, components/Header.vue, components/LeaveContact.vue, components/ui/ButtonFillForm.vue, components/ui/Menu.vue, components/ui/Sidebar.vue, pages/stories/_id.vue
переиспользовала меню в футере, поправила бэм, исправила подключение кнопки buttonfillform, поправила ссылки на картинки, логотип в хэдере сделала ссылкой
=> изменения после 2 ревью

components/Cardlist/CardList.vue, components/Pagination.vue, components/Stories.vue, pages/stories/_id.vue, pages/stories/index.vue
=> Pagination update

components/Cardlist/CardList.vue, components/Pagination.vue, components/Stories.vue, pages/stories/_id.vue, pages/stories/index.vue
убрала ограничение блока по ширине и убрала в Container
=> Stories component update

components/Cardlist/CardList.vue, components/Search.vue, pages/stories/_id.vue, pages/stories/index.vue
сорри за некорретное название ветки, увлеклась
приложу скрин в трелло с выполненными задачами
=> Section title update

components/Video/Video.vue, nuxt.config.js, pages/index.vue, store/video.js
Настроил env в nuxt.config.
Создал запрос video.
Теперь для видео данные загружаются с сервера и записываются в стор. 
на главной теперь они отображаются
=> Feature config env

components/Cardlist/CardList.vue, components/Pagination.vue, pages/stories/_id.vue
добавила первую и последнюю страницу и переключение по ним, немного стили
доделаю, сегодня не прет как-то)
=> немного добавила в пагинацию

components/Cardlist/CardList.vue, components/Pagination.vue, components/Statistics/Statistics.vue, components/TellStory.vue, components/TitleCoverBlock.vue, components/svg/buttonDown.vue, nuxt.config.js, package-lock.json, package.json, pages/index.vue, pages/stories/_id.vue, pages/stories/index.vue, static/arrow-down.svg, store/blocks.js
Так же перекинута svgшка buttonDown в компоненты, в папку svg, подчистила пакет
=> добавлен запрос для blocks, так же для statisctics & cover

pages/stories/_id.vue
в блоке рассказать историю и cover
удалила лишние стили и перепроверила, чтобы не было ошибок
=> удалила лишние стили

components/About.vue, components/Stories.vue, components/Video/Video.vue, components/ui/CoverBase.vue, pages/index.vue
Доделала объекты, плюс чуть верстку подправила в About
=> Blocks state more

layouts/error.vue, pages/stories/_id.vue
Добавил по макету нужную ошибку, оставив и подправив карточки разработчиков.
=> add error maket

components/Footer.vue, components/Header.vue, layouts/default.vue, middleware/basicData.js, nuxt.config.js, pages/index.vue
- в меню добавила "app-"
- футер вытащила в блокс
- для футера и хэдера внутри них прописала отдельные функции, которые находят данные, данные вставила в разметку
- добавила мидлвар и запрос в лэйауте
=> added computed for header and footer

components/LeaveContact.vue
=> Кнопка зависит от длины символов инпута

components/Pagination.vue, components/Search.vue, pages/stories/index.vue
Добавил начальный фильтр по ключевым словам,
полностью переделал пагинацию
=> create litle filter keysearch, and reformat logic pagination

components/Pagination.vue
теперь вроде как вообще без косяков в логике + верстка ок
=> верстка и логика

components/Pagination.vue, pages/stories/_id.vue
заметила баг в верстке, добавила неперенос строк 
поняла уже, что можно было здесь тоже заметить верстку через flex order, но это если успею сегодня
=> Social bug fix

middleware/README.md, middleware/basicData.js, middleware/requests.js, nuxt.config.js, pages/stories/index.vue, store/instagram.js
Сделал поиск по карточкам,
добавил проверки в мидлвару с запросами,  - убрались лишне запросы и вроде это помогло убртать ошибку 'user'
=> Feauture full search

components/ui/MoreArticles.vue
=> пофиксила кнопку больше статей

components/Cardlist/CardList.vue, components/Pagination.vue, pages/stories/index.vue
1. при отсутствии результатов поиска, появляется блок "нет резульаттов"
2. пагинация исчезает, если страниц меньше чем 2
=> create no-results logic and hidden pagination
